on:
  push:
    branches:
      - master
name: Release
jobs:
  #  release-on-push:
  #    runs-on: ubuntu-latest
  #    env:
  #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #    steps:
  #      - uses: rymndhng/release-on-push-action@master
  #        with:
  #          strategy: minor
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: version_tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liujordan/discordbot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: ${{ github.event_name != 'schedule' }}
          tags: "latest,${{ steps.version_tag.output.new_tag}}"